from enum import Enum

class SignalType(str, Enum):
    """High-level categories for intelligence signals."""
    HIRING = "HIRING"
    EXECUTIVE = "EXECUTIVE"
    FUNDING = "FUNDING"
    GITHUB = "GITHUB"
    LAUNCH = "LAUNCH"
    PARTNERSHIP = "PARTNERSHIP"
    NEWS = "NEWS"
    SOCIAL = "SOCIAL"

class SignalSubtype(str, Enum):
    """Specific event classifiers for intelligence."""
    # Hiring Intelligence
    AI_EXPANSION = "AI_EXPANSION"
    GTM_PUSH = "GTM_PUSH"
    REGIONAL_EXPANSION = "REGIONAL_EXPANSION"
    HIRING_FREEZE = "HIRING_FREEZE"
    LEADERSHIP_SURGE = "LEADERSHIP_SURGE"
    
    # Executive Movement
    CEO_APPOINTED = "CEO_APPOINTED"
    CEO_DEPARTED = "CEO_DEPARTED"
    CTO_APPOINTED = "CTO_APPOINTED"
    CTO_DEPARTED = "CTO_DEPARTED"
    CFO_APPOINTED = "CFO_APPOINTED"
    CFO_DEPARTED = "CFO_DEPARTED"
    COO_APPOINTED = "COO_APPOINTED"
    COO_DEPARTED = "COO_DEPARTED"
    CRO_APPOINTED = "CRO_APPOINTED"
    CRO_DEPARTED = "CRO_DEPARTED"
    BOARD_CHANGE = "BOARD_CHANGE"
    
    # Funding Events
    SEED = "SEED"
    SERIES_A = "SERIES_A"
    SERIES_B = "SERIES_B"
    SERIES_C = "SERIES_C"
    IPO = "IPO"
    ACQUISITION = "ACQUISITION"
    DEBT = "DEBT"
    
    # GitHub Velocity
    ENGINEERING_SURGE = "ENGINEERING_SURGE"
    RELEASE_ACCELERATION = "RELEASE_ACCELERATION"
    OPEN_SOURCE_EXPANSION = "OPEN_SOURCE_EXPANSION"
    MAINTENANCE_DECLINE = "MAINTENANCE_DECLINE"
    
    # Product Launches
    MAJOR_PRODUCT = "MAJOR_PRODUCT"
    MAJOR_FEATURE = "MAJOR_FEATURE"
    BETA = "BETA"
    INTEGRATION = "INTEGRATION"
    PRICING_CHANGE = "PRICING_CHANGE"
    
    # Partnerships
    STRATEGIC_PARTNERSHIP = "STRATEGIC_PARTNERSHIP"
    CLOUD_PARTNERSHIP = "CLOUD_PARTNERSHIP"
    AI_PARTNERSHIP = "AI_PARTNERSHIP"
    GOVERNMENT_CONTRACT = "GOVERNMENT_CONTRACT"

    # General Fallbacks
    GENERAL_NEWS = "GENERAL_NEWS"
    HACKER_NEWS = "HACKER_NEWS"
    REDDIT_POST = "REDDIT_POST"

class SignalStatus(str, Enum):
    """Lifecycle status of a signal."""
    ACTIVE = "ACTIVE"
    STALE = "STALE"
    SUPERSEDED = "SUPERSEDED"
    INVALIDATED = "INVALIDATED"